Fix updating fragment arrays multiple times in the same runloop (#487)
* run CI in production environment

* upgrade ember-try

Fixes the following error:
Error: Cannot copy '../../../browserslist/cli.js' to a subdirectory of itself, '../../../browserslist/cli.js'.
    at /home/runner/work/ember-data-model-fragments/ember-data-model-fragments/node_modules/ember-try/node_modules/fs-extra/lib/copy/copy.js:210:21
    at FSReqCallback.oncomplete (fs.js:180:23)

https://github.com/ember-cli/ember-try/issues/967

* upgrade to node.js 18

* fix store.find deprecation

* replace assert.throws with expectAssertion

* fix updating fragment array multiple times

* revert to node 14 and use `yarn --ignore-engines`